# project information
site_name: "Cookiecutter for KiCAD"
site_author: "Stephen Eaton"
site_description: "Cookiecutter Boilerplate for KiCAD Hardware projects"

# Page Tree
nav:
  - Home: index.md
  - Getting Started:
      - getting-started/requirements.md
      - getting-started/new-project.md
      - getting-started/github.md
      - getting-started/documentation.md
      - getting-started/project-structure.md
  - Contributing: contributing.md
  - Authors: authors.md
  - Change Log: changelog.md
  - License: license.md

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - header.autohide

# Repository
repo_name: "madeinoz67/cookiecutter-kicad"
repo_url: "https://github.com/madeinoz67/cookiecutter-kicad"
edit_uri: ""

# plugins
plugins:
  - search
  - mermaid2

extra_javascript:
  - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js

# extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Copyright
copyright: Copyright &copy; 2021 Stephen Eaton

# footer customisation
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/madeinoz67
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/madeinoz"

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
